@startuml

skinparam Shadowing false
skinparam ParticipantPadding 20
skinparam BoxPadding 10

skinparam sequence {
    ArrowColor DodgerBlue
    ActorBorderColor DodgerBlue
    LifeLineBorderColor Blue

    ParticipantBackgroundColor #3483eb
    ParticipantBorderColor #3483eb
    ParticipantFontSize 14
    ParticipantFontColor White

    ActorBackgroundColor #3483eb
    ActorFontSize 14
    NoteBackgroundColor #3483eb
}

hide footbox
autonumber

participant "ePA Aktensystem" as epa
participant "Vertrauensstelle\nRKI\n(VST)" as vst
participant "FDZ\nGesundheit\n(FDZ)" as fdz


activate epa

epa -> epa : create package_vst and package_fdz
epa -> vst : send package_vst with submissionID=x
activate vst
vst --> epa : OK. package_vst received
vst -> vst : translate LP to PÜP
vst -> vst: create package_püp with AN and PÜP
vst -> fdz : send package_püp with submissionID=x
activate fdz
fdz --> vst : OK
deactivate vst
alt FDZ ready for data
fdz -> epa : ready for data submissionID=x
epa --> fdz : send package_fdz for submissionID=x
else timeout
epa -> epa: restart process\nfor submissionID=x
end
deactivate fdz

deactivate epa



@enduml